development:
    adapter: postgresql
    encoding: unicode
    database: opened
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: postgres
    password: cabect

test:
    adapter: postgresql
    encoding: unicode
    database: opened
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: postgres
    password: cabect

production:
    adapter: postgresql
    encoding: unicode
    database: opened
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: postgres
    password: cabect